steps:
  - name: "eu.gcr.io/datalab/python"
    args: ["install", "github.com/betandr/datalab-python-docker-microservice"]
    env: ["PROJECT_ROOT=github.com/betandr/datalab-python-docker-microservice"]
  - name: "gcr.io/datalab/python"
    args: ["build", "-t", "gcr.io/datalab-python-docker-microservice/datalab-service:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/datalab-python-docker-microservice/datalab-service:$REVISION_ID"
